map_update_interval: 2.0
maxUrange: 3.0
sigma: 0.25
kernelSize: 5
lstep: 0.05
astep: 0.25
iterations: 5
lsigma: 0.075
ogain: 3.0
lskip: 0
minimumScore: 50
srr: 0.5
srt: 1.0
str: 0.5
stt: 1.0
linearUpdate: 5.0
angularUpdate: 0.2
temporalUpdate: 0.5
resampleThreshold: 2.5
particles: 150
xmin: -10.0
ymin: -10.0
xmax: 10.0
ymax: 10.0
delta: 0.01
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005
