TrajectoryPlannerROS:
    max_vel_x: 0.2
    min_vel_x: 0.05
    max_vel_theta: 2.0
    min_in_place_vel_theta: 0.5
  
    acc_lim_theta: 2.5
    acc_lim_x: 1.8
    acc_lim_y: 1.8
  
    holonomic_robot: false