transform_tolerance: 0.5
update_frequency: 5.0
publish_frequency: 5.0

global_frame: map
robot_base_frame: base_link
resolution: 0.05

rolling_window: false
track_unknown_space: true
 
plugins:
    - { name: static,           type: "costmap_2d::StaticLayer" }
    - { name: inflation,        type: "costmap_2d::InflationLayer" }
    - { name: obstacle_layer,   type: "costmap_2d::ObstacleLayer" }
    - { name: explore_boundary, type: "frontier_exploration::BoundedExploreLayer"}

static:
    enabled: true
    map_topic: "/map"

inflation:
    enabled: true
    cost_scaling_factor: 5
    inflation_radius: 0.3

obstacle_layer:
    observation_sources: laser_scan_sensor
    footprint_clearing_enabled: true
    laser_scan_sensor:
        {
            sensor_frame: camera_link,
            data_type: LaserScan,
            topic: scan,
            marking: true,
            clearing: true,
        }

explore_boundary:
    resize_to_boundary: false
    frontier_travel_point: middle
    explore_clear_space: false